name: CI
run-name: CI ğŸš€ğŸ•µï¸â€â™€ï¸
on: [push]

jobs:
  Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code ğŸ‘€
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - name: Run Validator HTML ğŸ‘¾
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
